/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.15
 * Generated at: 2015-05-20 19:02:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import com.dbutil.CrudOperation;
import java.sql.Connection;

public final class admin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");
//gtgt
    HttpSession hs;
hs=request.getSession(false);
if((String)hs.getAttribute("userinfo")==null)
{
	String s="<h1>Access Denied!!!</h1><br>Please do login first.<br><a href='/Sportsclub/jsp/user4.jsp'>Home Page</a>" ;



      out.write('\r');
      out.write('\n');
      out.print(s );
      out.write('\r');
      out.write('\n');
 }else 

{  
	
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("function aa()\r\n");
      out.write("{\r\n");
      out.write("document.write(\"alkdjk\");\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("function display(entity)\r\n");
      out.write("{\r\n");
      out.write("\tvar x;\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\tif(XMLHttpRequest)\r\n");
      out.write("\t{\r\n");
      out.write("\t\tx=new XMLHttpRequest();\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\telse\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\tx=new ActiveXObject(\"Microsoft.XMLHTTP\");\r\n");
      out.write("\t \r\n");
      out.write("\t\t}\r\n");
      out.write("\tx.onreadystatechange=function()\r\n");
      out.write("\t{\r\n");
      out.write("\t\tif(x.readyState==4&&x.status==200)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t   var info=x.responseText;\r\n");
      out.write("\t\t\t   document.getElementById(\"msgtxt\").innerHTML=info;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t};\r\n");
      out.write("\t\r\n");
      out.write("\tx.open(\"GET\", \"/Sportsclub/jsp/AjaxDisp.jsp?ent=\"+entity,\"true\");\r\n");
      out.write("\t//x.open(\"GET\", \"/Sportsclub/jsp/newmessage.jsp\",\"true\");\r\n");
      out.write("\t//x.open(, url, async, username, password)\r\n");
      out.write("\t//x.open(\"GET\", rl, async, username, password)\r\n");
      out.write("\tx.send();\r\n");
      out.write("\t//alert(x);\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"templatemo_wrapper\" style=\"height: 800px\">\r\n");
      out.write("\t<div id=\"tempelatemo_main\">\r\n");
      out.write("\t<h3>Welcome ");
      out.print(hs.getAttribute("username") +" <a style='Font-size:xx' href='/Sportsclub/LoginServ'>(Logout)</a>" );
      out.write("</h3>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"msgtxt\" class=\"img_frame img_frame_12 img_nom img_fl\"style=\"font-size: 16px;box-shadow:grey 8px 8px 8px;line-height: 30px;height:250px;width:70%\"><span></span>\r\n");
      out.write(" Hi, Admin. This panel provides you functionality to manage your users and website too. Make sure before changing any information in database because it can not be undone.\r\n");
      out.write("\t\r\n");
      out.write("        </div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"half right\"style=\"font-size: 16px;box-shadow:grey 8px 8px 8px;height:250px;width:25% \">\r\n");
      out.write("\t\t\t<h3>view Website Users</h3>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t <ul>\r\n");
      out.write(" \t\t<li>\t<input type=\"button\" value=\"Players List\" onclick=\"display('player');\"> </li>\r\n");
      out.write(" \t\t\t<li ><input type=\"button\" value=\"Coachs List\" onclick=\"display('coach');\">  </li>\r\n");
      out.write("            <li> <input type=\"button\" value=\"Players List\" onclick=\"display('expert');\"> </li> \r\n");
      out.write("            <!--  <li> <input type=\"button\" value=\"Users List\" onclick=\"display('user');\"> </li>\r\n");
      out.write("  -->\r\n");
      out.write(" </ul>\t</div>\r\n");
      out.write(" <div><br></div>\r\n");
      out.write("\t<div class=\"img_frame img_frame_12 img_nom img_fl\"style=\"font-size: 16px;box-shadow:grey 8px 8px 8px;line-height: 30px;height:250px;width:70%\"><span></span>\r\n");
      out.write("            <img src=\"/Sportsclub/images/templatemo_image_02.jpg\" alt=\"Model Girl 2\">\r\n");
      out.write("        </div>\r\n");
      out.write("\t<div class=\"half right\"style=\"font-size: 16px;box-shadow:grey 8px 8px 8px;height:250px;width:25%\">\r\n");
      out.write("\t<h3> Manage Enteties</h3>\r\n");
      out.write("<ol>\r\n");
      out.write("     \r\n");
      out.write("\t\t<li><a href=\"/Sportsclub/jsp/newmessage.jsp\"> Ask to  Expert</a> </li>\r\n");
      out.write("\t\t<li><a href=\"/Sportsclub/jsp/adminUpdate.jsp\"> Update User Profile</a></li>\r\n");
      out.write("\t\t<li><a href=\"/Sportsclub/jsp/delete.jsp\">Delete User</a></li>\r\n");
      out.write("\t\r\n");
      out.write("\t\t<li><a href=\"/Sportsclub/jsp/conv4.jsp\">Conversations</li>\r\n");
      out.write("\t\t<li><a href=\"/Sportsclub/jsp/requests.jsp\">View Requests</li>\r\n");
      out.write("\t\r\n");
      out.write("</ol>\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write('\r');
      out.write('\n');
 }
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
