/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.15
 * Generated at: 2015-05-20 19:04:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import com.dbutil.ConvRedirect;
import java.time.format.DateTimeFormatterBuilder;
import java.time.format.DateTimeFormatter;
import java.util.Calendar;
import java.util.Timer;
import java.sql.Time;
import java.util.Date;
import java.sql.SQLException;
import com.dbutil.CrudOperation;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.Connection;

public final class conv4_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/html/header.html", Long.valueOf(1407950450439L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<title>Inbox</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("var image1=new Image()\r\n");
      out.write("image1.src=\"/Sportsclub/images/1.jpg\"\r\n");
      out.write("var image2=new Image()\r\n");
      out.write("image2.src=\"/Sportsclub/images/a.jpeg\"\r\n");
      out.write("var image3=new Image()\r\n");
      out.write("image3.src=\"/Sportsclub/images/b.jpeg\"\r\n");
      out.write("var image4=new Image()\r\n");
      out.write("image4.src=\"/Sportsclub/images/4.jpg\"\r\n");
      out.write("var image5=new Image()\r\n");
      out.write("image5.src=\"/Sportsclub/images/5.jpg\"\r\n");
      out.write("var image6=new Image()\r\n");
      out.write("image6.src=\"/Sportsclub/images/6.jpg\"\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\t\t<link rel=\"icon\" href=\"/Sportsclub/images/sd.ico\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"/Sportsclub/css/nps.css\"/>\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"/Sportsclub/css/menu.css\"/>\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"/Sportsclub/css/temp.css\"/>\r\n");
      out.write("\t\t<link href=\"/Sportsclub/css/templatemo_style.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</head>\r\n");
      out.write("\t\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t <div id=\"whole_data\">\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<section id=\"top_name\">\r\n");
      out.write("\t\t\t\t\t <img src=\"logo.gif\" height=150px  align=left style=\"padding-left:150px; padding-top:0px;padding-bottom:0px\" >\r\n");
      out.write("\t\t\t\t\t <img src=\"logo2.jpg \" height=150px align=right style=\"padding-right:150px; padding-top:0px;padding-bottom:0px\" >\r\n");
      out.write("\t\t\t\t\t<div Style=\" font:BOLd 40px Elephant; color:white; padding:20px\"> Limfa Sports Club</div>\r\n");
      out.write("\t\t\t\t\t  <footer><h3 style=\"color:cyan; text-aign:left\"><i>Re-Defining Sports</i></h3></footer>\r\n");
      out.write("\t\t\t\t\t</section>\r\n");
      out.write("<!--   Menu ---------------------------------------------------------------------------------->\t\t\t\t\t\r\n");
      out.write("<div id='cssmenu'>\r\n");
      out.write("<ul>\r\n");
      out.write("   <li class='active'><a href='/Sportsclub/jsp/user4.jsp'>Home</a></li>\r\n");
      out.write("   <li class='has-sub'><a href='#'><span>Facilities</span></a>\r\n");
      out.write("      <ul>\r\n");
      out.write("         <li><a href='#'><span>Kits</span></a></li>\r\n");
      out.write("         <li><a href='#'><span>Expert's help</span></a></li>\r\n");
      out.write("         <li class='last'><a href='#'><span> Cards</span></a></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("   </li>\r\n");
      out.write("   <li class='has-sub'><a href='#'><span>Games</span></a>\r\n");
      out.write("      <ul>\r\n");
      out.write("         <li><a href=#><span>Cricket</span></a></li>\r\n");
      out.write("\t\t <li><a href=#><span>Hockey</span></a></li>\r\n");
      out.write("\t\t          <li><a href=#><span>Football</span></a></li>\r\n");
      out.write("         <li class='last'><a href='#'><span>Fifa fever</span></a></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("   </li>\r\n");
      out.write("   <li class='has-sub'><a href='#'><span>Services</span></a>\r\n");
      out.write("      <ul>\r\n");
      out.write("         <li><a href=#><span>Tournaments</span></a></li>\r\n");
      out.write("\t\t <li><a href=#><span>Coming Tournaments</span></a></li>\r\n");
      out.write("         <li class='last'><a href='#'><span>Results</span></a></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("   </li>\r\n");
      out.write("    <li class='has-sub'><a href='/Sportsclub/jsp/login.jsp'><span>Login</span></a>\r\n");
      out.write("      <ul>\r\n");
      out.write("         <li><a href=\"/Sportsclub/jsp/login.jsp\"><span>User login</span></a></li>\r\n");
      out.write("\t\t <li><a href=#><span>Coach Login</span></a></li>\r\n");
      out.write("         <li class=#><a href='#'><span>Player Login</span></a></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("   </li>\r\n");
      out.write("    <li class='has-sub'><a href='#'><span>Sign Up</span></a>\r\n");
      out.write("      <ul>\r\n");
      out.write("         <li><a href=\"/Sportsclub/jsp/userlogin.jsp\"><span>as a User</span></a></li>\r\n");
      out.write("\t\t <li><a href=\"/Sportsclub/jsp/registration.jsp\"><span>as A Coach</span></a></li>\r\n");
      out.write("         <li class=#><a href='/Sportsclub/jsp/registration.jsp'><span>AS a player/expert</span></a></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("   </li>\r\n");
      out.write("   \r\n");
      out.write("   <li class='has-sub'><a href=#><span>About us </span></a></li>\r\n");
      out.write("     \r\n");
      out.write("     \r\n");
      out.write("   \r\n");
      out.write("   <li class='last'><a href='#'><span>Contact us</span></a></li>\r\n");
      out.write("</ul>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("function display(entity)\r\n");
      out.write("{\r\n");
      out.write("\tvar x;\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\tif(XMLHttpRequest)\r\n");
      out.write("\t{\r\n");
      out.write("\t\tx=new XMLHttpRequest();\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\telse\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\tx=new ActiveXObject(\"Microsoft.XMLHTTP\");\r\n");
      out.write("\t \r\n");
      out.write("\t\t}\r\n");
      out.write("\tx.onreadystatechange=function()\r\n");
      out.write("\t{\r\n");
      out.write("\t\tif(x.readyState==4&&x.status==200)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t   var info=x.responseText;\r\n");
      out.write("\t\t\t   document.getElementById(\"msgtxt\").innerHTML=info;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t};\r\n");
      out.write("\t\r\n");
      out.write("\tx.open(\"GET\", \"/Sportsclub/jsp/AjaxMessage.jsp?ent=\"+entity,\"true\");\r\n");
      out.write("\t//x.open(\"GET\", \"/Sportsclub/jsp/newmessage.jsp\",\"true\");\r\n");
      out.write("\t//x.open(, url, async, username, password)\r\n");
      out.write("\t//x.open(\"GET\", rl, async, username, password)\r\n");
      out.write("\tx.send();\r\n");
      out.write("\t//alert(x);\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write(" function\tset(){\r\n");
      out.write("\t\t");

		 ConvRedirect.setRedirectedFrom("/Sportsclub/jsp/conv4.jsp");
		 
		
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

HttpSession hs;
hs=request.getSession(false);
String reciever=(String) hs.getAttribute("redirectFromConversationMessage");
if(reciever==null)
{
	
}
else{
	
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tdisplay('");
      out.print(reciever );
      out.write("');\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t");
 
}




PreparedStatement ps,ps2;
ResultSet rs,rs2;
Connection con;

con=CrudOperation.createConnection();
String conv=(String) hs.getAttribute("userinfo");

String q2="(select senderid from message where recieverid='"+conv+"' or senderid='"+conv+"'and senderid!=recieverid group by senderid )union(select recieverid from message where recieverid='"+conv+"' or senderid='"+conv+"'and senderid!=recieverid group by recieverid)";
//System.out.println(q2);
ArrayList<String> senderName=new ArrayList<String>();
ArrayList<Integer> messageTime=new ArrayList<Integer>();
try{

ps2=con.prepareStatement(q2);
rs2=ps2.executeQuery();
while(rs2.next())
{
	senderName.add(rs2.getString("senderid"));
}


      out.write("\r\n");
      out.write("<div id=\"templatemo_wrapper\" style=\"height:800px\" >\r\n");
      out.write("\t<div id=\"tempelatemo_main\">\r\n");
      out.write("\t<h3>Welcome ");
      out.print(hs.getAttribute("username") );
      out.write("</h3>\r\n");
      out.write("\t<div class=\"half right\"style=\"font-size: 16px;box-shadow:grey 8px 8px 8px;width:25%; \">\r\n");
      out.write("\t\t\t<h3>See Full Conversation</h3>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t <ul>\r\n");
      out.write("\t \t<a href=\"/Sportsclub/Reset\" onClick=\"set();\">Go Home</a>\r\n");
      out.write("\t");
for(int i=0;i<senderName.size();i++)
	 {
		
		String name=senderName.get(i);
		
		if(name.equals(conv))
		{
			//System.out.println("/////sjdksks"+conv);
		}
		else{
	
	 
	 
      out.write("\r\n");
      out.write(" \t\t<li>\t<input type=\"button\" value=\"");
      out.print(senderName.get(i) );
      out.write("\" onclick=\"display('");
      out.print(senderName.get(i));
      out.write("');\"> </li>\r\n");
      out.write(" \t\t       \r\n");
      out.write(" \t\t\r\n");
      out.write(" \t");

	 
		}
	 
	 }	


	
	
	
 
      out.write("\r\n");
      out.write(" </ul>\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"msgtxt\" class=\"img_frame img_frame_12 img_nom img_fl\"style=\"font-size: 16px;box-shadow:grey 8px 8px 8px;line-height: 30px;width:70%; \"><span></span>\r\n");
      out.write("\tThese people send message to you. Their last messages are following. Click on the sender's name to show full conversation.\r\n");
      out.write("\t\r\n");
      out.write("\t<em><h3>\r\n");


for(int k=0;k<senderName.size();k++)
{
	//if(!rs.getString("recieverid").equals(conv))
String q="Select sno from message where (recieverid='"+conv+"' or senderid='"+conv+"')  and (senderid='"+senderName.get(k)+"' or recieverid='"+senderName.get(k)+"')and timee in(Select max(timee) from message where (recieverid='"+conv+"' or senderid='"+conv+"')  and (senderid='"+senderName.get(k)+"' or recieverid='"+senderName.get(k)+"'))";
//System.out.println(q);
ps=con.prepareStatement(q);

rs=ps.executeQuery();		
		rs.next();
	

messageTime.add(rs.getInt("sno"));
}
final int size=messageTime.size();
int ank[]=new int[size];
for(int i=0;i<messageTime.size();i++)
{
ank[i]=messageTime.get(i);
}
int j;
for(int z=1;z<ank.length;z++)
{
int item=ank[z];
   for( j=z-1;j>=0 && ank[j]<item;j--)
   {  ank[j+1]=ank[j];}
ank[j+1]=item;
}
//for(int i=0;i<ank.length;i++)
	
	//System.out.println(ank[i]);
    
	for(int i=1;i<ank.length;i++)
{String finalq="Select * from message where sno='"+ank[i]+"'";

	PreparedStatement psf=con.prepareStatement(finalq);
	ResultSet rsf=psf.executeQuery();

	rsf.next();

      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"messagebox\" style=\"border: .9pt solid grey \">\r\n");

if(rsf.getString("recieverid").equals(conv))
{

      out.write("\r\n");
      out.write("<h3>");
      out.print(rsf.getString("senderid")  );
      out.write("</h3><h6>recieved</h6>\r\n");
}
else{
      out.write("\r\n");
      out.write("\r\n");
      out.write("<h3>");
      out.print(rsf.getString("recieverid") );
      out.write("</h3><h6>sent</h6>\r\n");
      out.write("\r\n");
} 
      out.write("\r\n");
      out.write(" <h4><tt>");
      out.print(rsf.getString("message") );
      out.write("</tt></h4>\r\n");
      out.write("\r\n");
 
Date day;
Date time;
day=rsf.getTimestamp("timee");
Date now=new Date();
Calendar nowCal=Calendar.getInstance();
Calendar thenCal=Calendar.getInstance();
thenCal.setTime(day);
if(thenCal.get(Calendar.DATE)==nowCal.get(Calendar.DATE))
{
      int hour=nowCal.get(Calendar.HOUR_OF_DAY)-thenCal.get(Calendar.HOUR_OF_DAY);
        {
					if(hour==0)
					{
						int min=nowCal.get(Calendar.MINUTE)-thenCal.get(Calendar.MINUTE);
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<h5 align=\"right\"><tt>");
      out.print(min );
      out.write(" minutes ago</tt></h5>\r\n");
      out.write("\t\t\t\t\t\t");

					}
					else{
					
      out.write("\r\n");
      out.write("\t\t      <h5 align=\"right\"><tt>today, ");
      out.print(hour );
      out.write(" hours ago</tt></h5>\r\n");
      out.write("                   \r\n");
      out.write("\t\t\t");

					}
			}
}		else{	
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<h5 align=\"right\">");
      out.print(String.format("%ta,%td %tB",day,day,day) );
      out.write('@');
      out.write(' ');
      out.print(String.format("%tI:%tM %tp",day,day,day) );
      out.write("</h5>\r\n");
} 
      out.write("\t\r\n");
      out.write("</div>\r\n");

	
}}
catch(SQLException se)
{
	System.out.println(se);
   //System.out.print();
}

      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write(" </div>\r\n");
      out.write(" </div>\r\n");
      out.write("</head>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
