/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.15
 * Generated at: 2015-05-20 18:19:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Login</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/Sportsclub/css/nps.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/Sportsclub/css/menu.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/Sportsclub/css/temp.css\"/>\r\n");
      out.write("<script type=\"text/javascript\">function fotter()\r\n");
      out.write("{\r\n");
      out.write("\tdocument.write('<div id=\"footer\">&copy; SportssClub | <a href=\"disclaimer.htm\">Disclaimer</a> | <a href=\"/Sportsclub/jsp/query.jsp\">Webmail</a> | </br>Powered by: <a target=\"_blank\" href=\" #><span class=\"bluFnt\"><span class=\"redfnt\"></span></span></a><a target=\"_blank\" href=\"#\"><span class=\"redfnt\"></span><span class=\"bluFnt\">Club Administrator</span> </a> </div>')\r\n");
      out.write("}</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body bgcolor=\"olive\">\r\n");
      out.write("\r\n");
      out.write("\t\t <div id=\"whole_data\">\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<section id=\"top_name\">\r\n");
      out.write("\t\t\t\t\t <img src=\"logo.gif\" height=150px  align=left style=\"padding-left:150px; padding-top:0px;padding-bottom:0px\" >\r\n");
      out.write("\t\t\t\t\t <img src=\"logo2.jpg \" height=150px align=right style=\"padding-right:150px; padding-top:0px;padding-bottom:0px\" >\r\n");
      out.write("\t\t\t\t\t<div Style=\" font:BOLd 40px Elephant; color:white; padding:20px\"> Limfa Sportss Club</div>\r\n");
      out.write("\t\t\t\t\t  <footer><h3 style=\"color:cyan; text-aign:left\"><i>Re-Defining Sportss</i> </h3></footer>\r\n");
      out.write("\t\t\t\t\t</section>\r\n");
      out.write("<!--   Menu ---------------------------------------------------------------------------------->\t\t\t\t\t\r\n");
      out.write("<div id='cssmenu'>\r\n");
      out.write("<ul>\r\n");
      out.write("   <li class='active'><a href='index.html'>Home</a></li>\r\n");
      out.write("   <li class='has-sub'><a href='#'><span>Facilities</span></a>\r\n");
      out.write("      <ul>\r\n");
      out.write("         <li><a href='#'><span>Kits</span></a></li>\r\n");
      out.write("         <li><a href='#'><span>Expert's help</span></a></li>\r\n");
      out.write("         <li class='last'><a href='#'><span> Cards</span></a></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("   </li>\r\n");
      out.write("   <li class='has-sub'><a href='#'><span>Games</span></a>\r\n");
      out.write("      <ul>\r\n");
      out.write("         <li><a href=#><span>Cricket</span></a></li>\r\n");
      out.write("\t\t <li><a href=#><span>Hockey</span></a></li>\r\n");
      out.write("\t\t          <li><a href=#><span>Football</span></a></li>\r\n");
      out.write("         <li class='last'><a href='#'><span>Fifa fever</span></a></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("   </li>\r\n");
      out.write("   <li class='has-sub'><a href='#'><span>Services</span></a>\r\n");
      out.write("      <ul>\r\n");
      out.write("         <li><a href=#><span>Tournaments</span></a></li>\r\n");
      out.write("\t\t <li><a href=#><span>Coming Tournaments</span></a></li>\r\n");
      out.write("         <li class='last'><a href='#'><span>Results</span></a></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("   </li>\r\n");
      out.write("    <li class='has-sub'><a href='#'><span>Login</span></a>\r\n");
      out.write("      <ul>\r\n");
      out.write("         <li><a href=#><span>User login</span></a></li>\r\n");
      out.write("\t\t <li><a href=#><span>Coach Login</span></a></li>\r\n");
      out.write("         <li class=#><a href='#'><span>Player Login</span></a></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("   </li>\r\n");
      out.write("   \r\n");
      out.write("   <li class='has-sub'><a href=#><span>About us </span></a></li>\r\n");
      out.write("     \r\n");
      out.write("     \r\n");
      out.write("   \r\n");
      out.write("   <li class='last'><a href='#'><span>Contact us</span></a></li>\r\n");
      out.write("</ul>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!------------------menu end------------------------->\r\n");
      out.write("<div style=\"top:300px; left: 550px; position: absolute;\">\r\n");
      out.write(" <form action=\"/Sportsclub/LoginServ\" method=\"post\">\r\n");
      out.write(" <table>\r\n");
      out.write(" <tr><th>Username</th> <td><input type=\"text\" name=\"id\" size=\"20\"></td></tr>\r\n");
      out.write(" <tr><th>password</th> <td><input type=\"password\" name=\"password\"></td> </tr>\r\n");
      out.write(" <tr><td colspan=\"2\"><a href=\"/Sportsclub/jsp/registration.jsp\">New Registration</a></td></tr>\r\n");
      out.write(" <tr><th colspan=\"2\"><input type=\"submit\" name=\"submit\" id=\"submit\" value=\"Log In\" /></th>\r\n");
      out.write(" </table>\r\n");
      out.write(" </form>\r\n");
      out.write("</div>\r\n");
      out.write("<footer style=\"background-color: maroon; width: 99.5%; bottom:0px; text-align:center;top:600px; position:absolute;border-radius:5px \">\r\n");
      out.write("<script type=\"text/javascript\">fotter();</script></footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
