/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.15
 * Generated at: 2015-05-20 19:21:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.dbutil.IsSet;
import java.sql.SQLException;
import com.bean.RegistrationBean;
import com.dbutil.CrudOperation;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Connection;

public final class update_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/html/footer2.html", Long.valueOf(1406227818236L));
    _jspx_dependants.put("/html/header.html", Long.valueOf(1407950450439L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<title>Update User Profile</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("var image1=new Image()\r\n");
      out.write("image1.src=\"/Sportsclub/images/1.jpg\"\r\n");
      out.write("var image2=new Image()\r\n");
      out.write("image2.src=\"/Sportsclub/images/a.jpeg\"\r\n");
      out.write("var image3=new Image()\r\n");
      out.write("image3.src=\"/Sportsclub/images/b.jpeg\"\r\n");
      out.write("var image4=new Image()\r\n");
      out.write("image4.src=\"/Sportsclub/images/4.jpg\"\r\n");
      out.write("var image5=new Image()\r\n");
      out.write("image5.src=\"/Sportsclub/images/5.jpg\"\r\n");
      out.write("var image6=new Image()\r\n");
      out.write("image6.src=\"/Sportsclub/images/6.jpg\"\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\t\t<link rel=\"icon\" href=\"/Sportsclub/images/sd.ico\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"/Sportsclub/css/nps.css\"/>\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"/Sportsclub/css/menu.css\"/>\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"/Sportsclub/css/temp.css\"/>\r\n");
      out.write("\t\t<link href=\"/Sportsclub/css/templatemo_style.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</head>\r\n");
      out.write("\t\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t <div id=\"whole_data\">\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<section id=\"top_name\">\r\n");
      out.write("\t\t\t\t\t <img src=\"logo.gif\" height=150px  align=left style=\"padding-left:150px; padding-top:0px;padding-bottom:0px\" >\r\n");
      out.write("\t\t\t\t\t <img src=\"logo2.jpg \" height=150px align=right style=\"padding-right:150px; padding-top:0px;padding-bottom:0px\" >\r\n");
      out.write("\t\t\t\t\t<div Style=\" font:BOLd 40px Elephant; color:white; padding:20px\"> Limfa Sports Club</div>\r\n");
      out.write("\t\t\t\t\t  <footer><h3 style=\"color:cyan; text-aign:left\"><i>Re-Defining Sports</i></h3></footer>\r\n");
      out.write("\t\t\t\t\t</section>\r\n");
      out.write("<!--   Menu ---------------------------------------------------------------------------------->\t\t\t\t\t\r\n");
      out.write("<div id='cssmenu'>\r\n");
      out.write("<ul>\r\n");
      out.write("   <li class='active'><a href='/Sportsclub/jsp/user4.jsp'>Home</a></li>\r\n");
      out.write("   <li class='has-sub'><a href='#'><span>Facilities</span></a>\r\n");
      out.write("      <ul>\r\n");
      out.write("         <li><a href='#'><span>Kits</span></a></li>\r\n");
      out.write("         <li><a href='#'><span>Expert's help</span></a></li>\r\n");
      out.write("         <li class='last'><a href='#'><span> Cards</span></a></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("   </li>\r\n");
      out.write("   <li class='has-sub'><a href='#'><span>Games</span></a>\r\n");
      out.write("      <ul>\r\n");
      out.write("         <li><a href=#><span>Cricket</span></a></li>\r\n");
      out.write("\t\t <li><a href=#><span>Hockey</span></a></li>\r\n");
      out.write("\t\t          <li><a href=#><span>Football</span></a></li>\r\n");
      out.write("         <li class='last'><a href='#'><span>Fifa fever</span></a></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("   </li>\r\n");
      out.write("   <li class='has-sub'><a href='#'><span>Services</span></a>\r\n");
      out.write("      <ul>\r\n");
      out.write("         <li><a href=#><span>Tournaments</span></a></li>\r\n");
      out.write("\t\t <li><a href=#><span>Coming Tournaments</span></a></li>\r\n");
      out.write("         <li class='last'><a href='#'><span>Results</span></a></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("   </li>\r\n");
      out.write("    <li class='has-sub'><a href='/Sportsclub/jsp/login.jsp'><span>Login</span></a>\r\n");
      out.write("      <ul>\r\n");
      out.write("         <li><a href=\"/Sportsclub/jsp/login.jsp\"><span>User login</span></a></li>\r\n");
      out.write("\t\t <li><a href=#><span>Coach Login</span></a></li>\r\n");
      out.write("         <li class=#><a href='#'><span>Player Login</span></a></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("   </li>\r\n");
      out.write("    <li class='has-sub'><a href='#'><span>Sign Up</span></a>\r\n");
      out.write("      <ul>\r\n");
      out.write("         <li><a href=\"/Sportsclub/jsp/userlogin.jsp\"><span>as a User</span></a></li>\r\n");
      out.write("\t\t <li><a href=\"/Sportsclub/jsp/registration.jsp\"><span>as A Coach</span></a></li>\r\n");
      out.write("         <li class=#><a href='/Sportsclub/jsp/registration.jsp'><span>AS a player/expert</span></a></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("   </li>\r\n");
      out.write("   \r\n");
      out.write("   <li class='has-sub'><a href=#><span>About us </span></a></li>\r\n");
      out.write("     \r\n");
      out.write("     \r\n");
      out.write("   \r\n");
      out.write("   <li class='last'><a href='#'><span>Contact us</span></a></li>\r\n");
      out.write("</ul>\r\n");
      out.write("</div>\r\n");
      out.write('\r');
      out.write('\n');


Connection con=null;
HttpSession hs;
String sql;
hs=request.getSession(false);
RegistrationBean rb=new RegistrationBean();
if(IsSet.isFromAdminUpdate()==1)
{
sql="select*from registration where userid='"+IsSet.getEntity()+"'";
IsSet.resetFromAdminUpdate();
}
else 
{
 sql="select*from registration where userid='"+hs.getAttribute("userinfo")+"'";}
System.out.println(sql);
ResultSet rs;
PreparedStatement ps;
con=CrudOperation.createConnection();
try{
ps=con.prepareStatement(sql);
rs=ps.executeQuery();
while(rs.next())

{
	rb.setId(rs.getString("userid"));
	rb.setName(rs.getString("name"));
	rb.setGame(rs.getString("game"));
	rb.setPhone(Long.parseLong(rs.getString("phone")));
	rb.setIdtype(rs.getString("idtype"));
	rb.setIdno(rs.getString("idno"));
	rb.setRole(rs.getString("role"));
	rb.setGender(rs.getString("sex"));
	rb.setAddr(rs.getString("address"));
}
}
catch(SQLException se)
{
	System.out.println(se);
}


      out.write("\r\n");
      out.write("\t <div id=\"templatemo_main\">\r\n");
      out.write("\r\n");
      out.write("       \r\n");
      out.write("       \r\n");
      out.write("\t\t\t\t\t<nav id= \"bigger_border\">\r\n");
      out.write("\t\t<article id=\"news\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<form name=\"mf\" action=\"/Sportsclub/UpdateServ\" method=\"post\" style=\"background:white; cellpadding:10px\">\r\n");
      out.write("\t\t\t\t\t\t<marquee direction=\"left\" width=\"100%\" scrollamount=\"3\" onmouseover=\"this.stop()\" onmouseout=\"this.start()\" style=\"padding-top:20px\">\r\n");
      out.write("        <b style=\"background:#eeebdd; font-variant:small-caps; font-size:14px;\">Please fill genuine informations......</b>\r\n");
      out.write("        </marquee>\r\n");
      out.write("\t\t\t\t\t\t<table  cellpadding=\"10\" cellspacing=\"4\"  width=\"100%\">\r\n");
      out.write("\t\t\t\t\t\t<center> \r\n");
      out.write("\t\t\t\t\t\t\t<caption align=\"top\"><h2> Update Detail</h2> </caption>\r\n");
      out.write("\t\t\t\t\t\t</center>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>NAME </TD>\r\n");
      out.write("\t\t\t\t\t\t\t<Td><input type=\"text\" name=\"name\" value=\"");
      out.print(rb.getName());
      out.write("\" ></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Sport Name</TD>\r\n");
      out.write("\t\t\t\t\t\t\t<Td><input type=\"text\"placeholder=\"your desired game's name\" name=\"game\"  value=\"");
      out.print(rb.getGame());
      out.write("\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Email id </TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"id\" value=\"");
      out.print(rb.getId() );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t<Td>");
      out.print(rb.getId() );
      out.write("<h6 style=\"color: red\">This can't be changed</h6> </td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Contact No. </TD>\r\n");
      out.write("\t\t\t\t\t\t\t<Td><input type=\"text\" name=\"phone\"  value=\"");
      out.print(rb.getPhone() );
      out.write("\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr><td>Id Proof</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\t<select name=\"idtype\">\r\n");
      out.write("\t\t <option  value=\"");
      out.print(rb.getIdtype() );
      out.write('"');
      out.write('>');
      out.write(' ');
      out.print(rb.getIdtype() );
      out.write(" </option>\r\n");
      out.write("\t\t<option  value=\"Driving License</\">Driving License</option>\r\n");
      out.write("\t\t<option value=\"Acadamic Certificate\">Acadamic Certificate</option>\r\n");
      out.write("\t\t<option value=\"Pan Card \">Pan Card </option>\r\n");
      out.write("\t\t<option value=\"other\">Other</option>\r\n");
      out.write("\t\t</select></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>Id no.</TD>\r\n");
      out.write("\t\t\t\t\t\t\t<Td><input type=\"number\" name=\"idno\"  value=\"");
      out.print(rb.getIdno() );
      out.write("\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Address </TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><textarea rows=\"3\" cols=\"30\" name=\"address\"> ");
      out.print(rb.getAddr() );
      out.write(" </textarea> </td>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Sex </TD>\r\n");
      out.write("\t\t\t\t\t\t\t<Td><input type=radio name=\"gender\" value=male Checked>Male\r\n");
      out.write("\t\t\t\t\t\t\t    <input type=radio name=\"gender\" value=female>female\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Account type </TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\t<select name=\"role\">\r\n");
      out.write("\t\t<option value=\"");
      out.print(rb.getRole());
      out.write('"');
      out.write(' ');
      out.write('>');
      out.print(rb.getRole() );
      out.write("</option>\r\n");
      out.write("\t\t<option value=\"user\">User Account</option>\r\n");
      out.write("\t\t<option value=\"player\">Player Account</option>\r\n");
      out.write("\t\t<option value=\"coach \">Coach Account</option>\r\n");
      out.write("\t\t<option value=\"expert\">Expert's Account</option>\r\n");
      out.write("\t\t</select></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>Choose Your password </TD>\r\n");
      out.write("\t\t\t\t\t\t\t<Td><input type=\"Password\" name=\"password\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>Repeat Your password </TD>\r\n");
      out.write("\t\t\t\t\t\t\t<Td><input type=\"Password\" name=\"\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr> \r\n");
      out.write("\t\t\t\t\t\t\t<td> <input type=\"hidden\" value=\"1\" name=\"fromupdate\"> </td>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t    \r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"Submit\" value=\"Submit\">\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t</article>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</nav>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");
      out.write("<div id=\"templatemo_footer_wrapper\">\r\n");
      out.write("    <div id=\"templatemo_footer\" style=\"text-align:right\"><h6>\r\n");
      out.write("    \t<p>Copyright 2014 <a href=\"https://www.facebook.com/prashant.singh.501151\"><i>SportsClub</i> </a></br> <br>\r\n");
      out.write("        \tAll rights reserved by<a rel=\"nofollow\" href=\"http://www.thakurprashantsingh.webs.com\">Club Administator</a>  </p></h6>\r\n");
      out.write("    </div><!-- END of templatemo_footer -->\r\n");
      out.write("</div><!-- END of templatemo_footer_wrapper -->\r\n");
      out.write("\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t</body>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
